apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-petclinic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
